### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by asdfladskfdjkfdsahfjkfh** [system76/pop-distro#1]
Hello! I wondering about the License for this project and if I have the rights to fork and redistribute it. Thanks.

**Comment by kylerschin** [comment]
yeah... MIT would be great. or at least Mozilla. (**pissttt.*** GPL is to restrictive *whispers))

**Comment by cassidyjames** [comment]
It looks like [LICENSE.md](https://github.com/system76/distro/blob/master/LICENSE.md) was added to the repo.

**Comment by kylerschin** [comment]
Awesome!
