### ISSUE TITLE
Geary and Online account sync : Gmail account not added.

### ISSUE THREAD

**Issue by 1Claude** [system76/pop-distro#100]
After setting my Google account on install, I thought that it would have been added to Geary as well, like it usually does with Evolution.

Not a big deal, maybe a fine tuning, if possible.

**Comment by shaggytwodope** [comment]
Not all software (Geary for example) makes use of the gnome online accounts backend (which evolution does). Which is most likely the case here.

This is not avoidable, not all projects can or will support such features.

**Comment by WatchMkr** [comment]
Thanks for the bug report. Default apps should make use of Online Accounts. We'll be reviewing email clients once again for the 18.04 release. Closing for now as that review will be on our 18.04 roadmap.
