### ISSUE TITLE
Too many keyboard shortcuts triggering TTY change

### ISSUE THREAD

**Issue by HarlemSquirrel** [system76/pop-distro#106]
**Reporter info**
Pop!_OS 17.10
installed yesterday
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Artful Aardvark (development branch)
Release:	17.10
Codename:	artful
```

**Issue/Bug Description**
Some keyboard shortcuts involving alt are not working. For instance alt + left arrow in Firefox traditionally navigates back but now is cycling TTY backward and alt + right arrow cycles forward. Also, super + left/right arrow does the same. 

Alt + F4 traditionally closes an application but is now jumping to TTY4 like ctrl + alt + F4 does.

**Comment by jackpot51** [comment]
That is very odd, as those shortcuts should not be present inside of X. Please attach the output of `sudo dumpkeys` and we will take a look at it as soon as possible.

**Comment by HarlemSquirrel** [comment]
Sure, thanks for the quick response! Also, I'm using a Kudu laptop. 

```
[keysdump-2017.09.30.txt](https://github.com/system76/pop-distro/files/1346505/keysdump-2017.09.30.txt)

System Information
	Manufacturer: System76, Inc.
	Product Name: Kudu
	Version: kudu3
```

**Comment by WatchMkr** [comment]
@HarlemSquirrel I also had this problem. After running updates and rebooting alt+left/right and super+left/right no longer trigger TTY change. Can you verify it's fixed as well?

**Comment by HarlemSquirrel** [comment]
This seems to be working after updating today. Thanks!
