### ISSUE TITLE
Buttons doesn't fit nicely inside of screen

### ISSUE THREAD

**Issue by nrsimha** [system76/pop-distro#107]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

Issue is on https://d1vhcvzji58n1j.cloudfront.net/pop-os/iso/beta/27/pop-os_amd64_27.iso

**Issue/Bug Description**

Some of the buttons during installation is visible only partially.

![screenshot](https://user-images.githubusercontent.com/2452933/31047484-d78a9f90-a60b-11e7-8ff5-b88f060f0f40.png)

**Steps to reproduce (if you know)**

Run installation in Parallels.

**Expected behaviour**

All buttons should fit on the screen.

**Comment by WatchMkr** [comment]
Does expending the Parallels parent window expose the interface buttons? 

Automatic scaling like that won't arrive until the new display server Wayland is used and a new installer that runs on Wayland is completed.
