### ISSUE TITLE
Chrome tab and context menu text dimmed

### ISSUE THREAD

**Issue by Appalbarry** [system76/pop-distro#108]
barryrueger@pop-os:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Artful Aardvark (development branch)
Release:	17.10
Codename:	artful

Chrome Version 61.0.3163.100 (Official Build) (64-bit)
```
**Issue/Bug Description**

Text in tabs is dimmed.
Text in context (right click) menus is dimmed as of unavailable.
![image](https://user-images.githubusercontent.com/1308152/31048701-a049910a-a5d7-11e7-9715-cb239f52054f.png)

**Steps to reproduce (if you know)**

Install Chrome
Launch Chrome.

**Expected behaviour**
Text display properly.


**Other Notes**

**Comment by isantop** [comment]
This is fixed as of system76/pop-gtk-theme@31691ccbc39446b5a276548124778b2a8eac0e14
