### ISSUE TITLE
Ubiquity > Make it as small as possible (Leave user setup to GNOME Initial Setup)

### ISSUE THREAD

**Issue by WatchMkr** [system76/pop-distro#11]
Remove connect to a network. Add language packs to the .iso
Remove KB layout
Remove download updates and install 3rd party software (download .iso will be updated daily. Codecs can be installed after installation)

**Comment by WatchMkr** [comment]
Skip button doesn't seem to do anything. Possibly remove.

**Comment by WatchMkr** [comment]
Remove "remove media and press enter to reboot prompt". (Just reboot)

**Comment by jbicha** [comment]
>  Remove KB layout

Keyboard layout is needed before enabling full-disk encryption (or custom partitioning). (Yes, it's a [bug](https://launchpad.net/bugs/1529276) that ubiquity doesn't exactly work like that now.)

What you might want is for ubiquity (Ubuntu's graphical installer) to pass the keyboard layout selection to Initial Setup some how.

For some of the other changes, I think your developers will need to figure out if they really want to fork ubiquity (my initial opinion is that they probably don't want to). If not, then they'll need to find a way to work with ubiquity upstream.

ubiquity does have a very through [Design Spec](https://wiki.ubuntu.com/Ubiquity) so y'all should probably talk to the Designers about decisions you want to influence.

**Comment by jbicha** [comment]
My understanding of the "Download updates" choice is that it installs security updates for you before you boot for the first time after installing. (I'm not sure if it used to work differently.) And if that's all it does, maybe you're right and it should just do it and not bother asking you.

But the other question on that page is special in that there isn't any obvious place (yet) where you can opt in or opt out of that setting after install. (Behind the scenes it installs `ubuntu-restricted-addons`, a metapackage to install Flash, Fluendo's mp3 support, Chromium extra codecs, and the gstreamer libav, bad and ugly plugins.)

**Comment by WatchMkr** [comment]
> Keyboard layout is needed before enabling full-disk encryption (or custom partitioning). (Yes, it's a bug that ubiquity doesn't exactly work like that now.)

Yes, it would be great to type your password with the correct layout. We think KB layout belongs in the iso boot screen that way you're setup correctly from the get go. What do you think?

We also think language packs should be included in the iso but of course it gets much larger. It seems like the only way to truly support multiple languages reliably.
 
> My understanding of the "Download updates" choice is that it installs security updates for you before you boot for the first time after installing. (I'm not sure if it used to work differently.) And if that's all it does, maybe you're right and it should just do it and not bother asking you.

Download updates tends to break and doesn't fail well. There are probably better ways to handle this - with fresh iso's or prompting to upgrade on first network connection.

> But the other question on that page is special in that there isn't any obvious place (yet) where you can opt in or opt out of that setting after install. (Behind the scenes it installs ubuntu-restricted-addons, a metapackage to install Flash, Fluendo's mp3 support, Chromium extra codecs, and the gstreamer libav, bad and ugly plugins.) 

We've had some issues with this feature. Similar to download updates, it breaks often and doesn't fail well. And things have changed significantly since the feature was conceived. This approach might deserve a rethink for how things are today. 

We've had security and quality issues with Flash for a long time. We don't pre-install on hardware any longer and have had little to no blow back from the decision. My understanding is that the MP3 patent is up and it's now free to distribute - just my understanding WE NEED TO VERIFY. But if true, we can pre-install if we so chose. Ubuntu also has a great feature to install codecs when they're first used. That seems like a solid way to install what's necessary with out the codec-metapackage approach.

**Comment by WatchMkr** [comment]
> For some of the other changes, I think your developers will need to figure out if they really want to fork ubiquity (my initial opinion is that they probably don't want to). If not, then they'll need to find a way to work with ubiquity upstream.

We'd much rather not fork anything. Hopefully we're making an improved install experience that the Ubiquity and Ubuntu team will agree with. If there's a better approach, let us know. (We took this one up right away because the Ubiquity + GNOME Initial Setup duplication isn't an out of box experience we want to ship to our customers).

**Comment by jbicha** [comment]
> We think KB layout belongs in the iso boot screen that way you're setup correctly from the get go.

I think the ISO boot screen is not accessible to people who are blind.

The Ubuntu Desktop team plans to discuss language packs soon. Several languages have been completely available in the ISO since 16.04 LTS, but that made the ISO ~200MB larger. And we might need another 100 MB or more now to keep them completely installed.

But come talk to Ubuntu about these suggestions. Some times Ubuntu may have good reasons for their decisions; some times Ubuntu may be willing to make the changes you suggest.

**Comment by WatchMkr** [comment]
Ubiquity panels were reduced though there is still some duplication. Completed for 17.10. For 18.04 we'll transition to a new installer.
