### ISSUE TITLE
Airplane Mode problems on 17.04

### ISSUE THREAD

**Issue by jwinnie** [system76/pop-distro#114]
**Reporter info**

```
 * Distribution - Pop!_OS (Ubuntu 17.04 Zesty)
 * GNOME Shell 3.24.2
 * Laptop - HP Spectre x360
```

**Issue/Bug Description**
After waking from suspend, a large banner is displayed that says "Airplane Mode Disabled" and "WiFi Connection established". Then, it says "Airplane Mode Enabled" and "WiFi Connection Lost". I then have to manually toggle WiFi back on.

**Steps to reproduce (if you know)**
Use Pop!_OS on a laptop. Click suspend, then wake the computer.

**Expected behaviour**
GNOME should automatically enable/disable WiFi and Bluetooth on suspend/wake without needing input from the user.

**Other Notes**
I tried this on both GNOME and Budgie and it happens on both.

**Comment by WatchMkr** [comment]
Hi @jwinnie - 17.04 was an alpha release that has now been superseded by the 17.10 beta. Please try the latest release.

https://system76.com/pop
