### ISSUE TITLE
Pop doesn't work on EFI computers.

### ISSUE THREAD

**Issue by Justin00015** [system76/pop-distro#117]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - Ubuntu Artful Aardvark
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```

**Issue/Bug Description**
When testing Pop OS on a VM with EFI enabled, all you get is the startup screen for a few seconds and then a black screen for forever.

**Steps to reproduce (if you know)**
Installed on a VM with EFI enabled

**Expected behaviour**
Computer should should show the startup screen fully and boot normally

**Other Notes**
Pop OS does work on a VM when "Enable EFI" is disabled. Tested on VirtualBox

**Comment by jackpot51** [comment]
This should be fixed, once a new ISO is generated

**Comment by jackpot51** [comment]
@Justin00015 please try the newest ISO here:

Intel/AMD: https://d1vhcvzji58n1j.cloudfront.net/pop-os/iso/beta/31/pop-os_amd64_31.iso

NVIDIA: https://d1vhcvzji58n1j.cloudfront.net/pop-os/iso/beta_nvidia/22/pop-os_amd64_nvidia_22.iso

**Comment by RicardoEPRodrigues** [comment]
Hi again,

It does not allow me to boot with secure boot ON (note that I do not have a System 76 laptop). The message is as follows:

```
Secure Boot Violation

Invalid signature detected. Check Secure Boot Policy in Setup.
```

Other than that it seems to go smoothly. (At least on NVidia)

**Comment by jackpot51** [comment]
That is odd @RicardoEPRodrigues. Does the Intel ISO or Ubuntu 17.10 work on your machine with Secure Boot? We tested the new ISO on a number of Secure Boot enabled systems.

**Comment by RicardoEPRodrigues** [comment]
Hi again, I tested it out. It seems the Ubuntu works like a charm, yet your ISO don't have a valid signature.

I'm testing this on a MSI GS70 Stealth Pro. It's not very Linux friendly.

**Comment by jackpot51** [comment]
Thanks, I will compare the two

**Comment by jackpot51** [comment]
I identified some differences in the two ISOs that I will attempt to fix.

**Comment by jackpot51** [comment]
New ISOs are being built that will work on the majority of secure boot systems. There are some buggy EFI implementations that hardcode the location of the bootloader to a Windows-specific path that will remain broken.

**Comment by jackpot51** [comment]
Build 33 should fix secure boot

**Comment by rohitghali** [comment]
It has been 12 months and this is still not fixed. I still get the efi secure boot failed error while dualbooting with Windows 10. Ubuntu works fine. Please fix it. I used Acer aspire 5.

**Comment by spontaliku-softaria** [comment]
I cannot boot into installed OS too. After successful installation I reboot and see boot options with Pop OS among them which is not working - nothing happens after choosing.

Lenovo E480. One of attempts was complete formatting of disc and choosing "Erase all" option in installer - no luck.

**Comment by stefanooliveira** [comment]
> It has been 12 months and this is still not fixed. I still get the efi secure boot failed error while dualbooting with Windows 10. Ubuntu works fine. Please fix it. I used Acer aspire 5.

Same thing here. It's 2022 guys. What's going on with Acer aspire 5 and PopOS? Shoud be fixed by now.
