### ISSUE TITLE
Bootable USB stuck at grub

### ISSUE THREAD

**Issue by jose-sanchezm** [system76/pop-distro#120]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

HP Pavilion dv6 from 2012
Core i7
8GB RAM
Samsung SSD 850 EVO
1 partition with Windows 10
1 partition with elementaryOS Loki
1 swap partition
1 NTFS partition
Bootable USB created with Etcher from pop-os_amd64_27.iso

```
 * Distribution - (run ```lsb_release -a```)
N/A
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
N/A
```

**Issue/Bug Description**

When trying to boot with the aforementioned USB drive, the system gets stuck at boot. It just shows the letters "GRUB" and it stops. Nothing works and a hard reset is necessary in order to reboot the computer.

**Comment by WatchMkr** [comment]
Does removing "quiet splash" from the grub line allow you to boot?

Please provide the output of `lspci`

**Comment by jackpot51** [comment]
This should be fixed when a new ISO is built

**Comment by jackpot51** [comment]
@jose-sanchezm please try the newest ISO here:

Intel/AMD: https://d1vhcvzji58n1j.cloudfront.net/pop-os/iso/beta/31/pop-os_amd64_31.iso

NVIDIA: https://d1vhcvzji58n1j.cloudfront.net/pop-os/iso/beta_nvidia/22/pop-os_amd64_nvidia_22.iso
