### ISSUE TITLE
File Manager Lacks Help and About

### ISSUE THREAD

**Issue by Appalbarry** [system76/pop-distro#123]
While preparing the previous bug report, I found that the File Manager included with Pop! lacks menu options for "Help" or "About".  There is nothing to identify the actual program or version. (Nautilus? Nemo?)

![screenshot from 2017-10-07 10-33-43](https://user-images.githubusercontent.com/1308152/31310347-8a6bf17e-ab4b-11e7-8ccb-d178be0427c9.png)

**Issue/Bug Description**

File Manager lacks title bar with program name.
App menu lacks "Help" or "About" options.

**Steps to reproduce (if you know)**

Open the app.

**Expected behaviour**

Title Bar will display program name
App menu will include an "About" option that displays program details and version number.

**Other Notes**

**Comment by Appalbarry** [comment]
Ah, the Help and About menu items are found in the drop down menu from the top menu bar, not from the menu contained in the app.
![screenshot from 2017-10-07 12-34-15](https://user-images.githubusercontent.com/1308152/31311201-0e938286-ab5c-11e7-80c6-b77fd1c48ef2.png)

I guess that having long ago abandoned Apple for Windows, then Linux (Mint variety) I assume that application specific menu items are contained within the app environment, not the external; menu bar.

I don't know whether this is a Gnome thing, or a Pop! thing, but consistency across the system would be a good thing.  Some applications have Help and About in the app, Files doesn't.

**Comment by WatchMkr** [comment]
Thanks for the feedback. This is the GNOME menu design. We're considering conducting a menu study to determine if or where improvements can be made.
