### ISSUE TITLE
Installer release notes points to an Ubuntu site

### ISSUE THREAD

**Issue by sarahpandabeara** [system76/pop-distro#128]

**Comment by sarahpandabeara** [comment]
Update to point to the proper location.

**Comment by jackpot51** [comment]
What is the proper location?

**Comment by WatchMkr** [comment]
Change the release notes link to copy > "Welcome to Pop!_OS. Choose your language to continue."

**Comment by jackpot51** [comment]
If we have a website to point to, that will make the patch very fast to implement. The URL simply comes from a file on the ISO, which currently contains

http://www.ubuntu.com/getubuntu/releasenotes?os=ubuntu&ver=17.10&lang=${LANG}

**Comment by jackpot51** [comment]
Removing that file removes the release notes link in Ubiquity

**Comment by jackpot51** [comment]
Addressed in https://github.com/system76/pop-distro/commit/e7a666fb8ee2bad99fd859c1ee44c59ce376bc44
