### ISSUE TITLE
"Powerwash" -> Erase Everything, get Fresh Install

### ISSUE THREAD

**Issue by ryanleesipes** [system76/pop-distro#14]
**Feature Request**

ChromeOS has a feature called "Powerwash" that erases all user information on the machine and gives you what is essentially a fresh install. I'm hoping with the Initial User Setup we could do something like this that involves just erasing existing users and boom, you're back at setup. As far as what to do with existing data, I'm not sure. But we could call it NIFS (Nuke it from Space). ;)

**Comment by isantop** [comment]
I like the idea of "Nuke from orbit" or "steam cleaning" or something similar. We might have to look into this a bit, since I'm not sure we could as easily remove installed packages, but I really like the idea.

**Comment by ryanleesipes** [comment]
Oooo "Steam Cleaning", I like that. Wonder what @jackpot51 thinks?

**Comment by WatchMkr** [comment]
Please discuss feature request via our Pop!_OS subreddit.

https://www.reddit.com/r/pop_os/
