### ISSUE TITLE
Location Services should be disabled by default

### ISSUE THREAD

**Issue by brs17** [system76/pop-distro#144]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 31 (noNVIDIA)

**Issue/Bug Description**
The "Location Services" toggle should be defaulted to off during installation. 

**Steps to reproduce (if you know)**

**Expected behaviour**

**Other Notes**

**Comment by WatchMkr** [comment]
We'll have a separate bug for creating better language for location services but it probably should not be off by default. This would negatively affect Night Light and Weather location services.
