### ISSUE TITLE
Can't disable edge tiling

### ISSUE THREAD

**Issue by leehblue** [system76/pop-distro#149]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**
Lee Blue

```
 * Distribution - (run ```cat /etc/os-release```)
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/system76/pop-distro/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```

**Issue/Bug Description**

Unable to turn off edge-tiling

**Steps to reproduce (if you know)**

Launch dconf-editor 
Navigate to /org/gnome/shell/overrides
Turn off "edge-tiling"
Log out
Log in
Edge Tiling still works

**Expected behaviour**

Edge tiling should be disabled

**Other Notes**

**Comment by jackpot51** [comment]
The correct setting is in /org/gnome/mutter edge-tiling

**Comment by leehblue** [comment]
Awesome! That worked. Thanks!
