### ISSUE TITLE
Pop!_OS Installation > Remove pause at the end of installation

### ISSUE THREAD

**Issue by WatchMkr** [system76/pop-distro#17]
Don't stop and prompt to remove media. Just reboot.

**Comment by JosephMcc** [comment]
It serves a purpose though. If you reboot with removal of the installation media, you will just reboot back into the installer.

**Comment by yarrgh** [comment]
Not if you don't have your media set as the default boot device

**Comment by WatchMkr** [comment]
Will be completed in 18.04 with the new installer.
