### ISSUE TITLE
Pop Shop Updater Displays Items Multiple Times

### ISSUE THREAD

**Issue by Appalbarry** [system76/pop-distro#171]
* Distribution - (run ```cat /etc/os-release```)
barryrueger@pop-os:~$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/system76/pop-distro/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

 **Issue/Bug Description**

Pop_Shop sometimes displays the same update item multiple times. Two, four, six, or more times.

**Steps to reproduce (if you know)**
Open the Pop_Shop Update page when updates are pending

**Expected behaviour**
Items to be updated are shown only once.

**Other Notes**
![screenshot from 2017-10-17 17-56-36](https://user-images.githubusercontent.com/1308152/31696345-5bebfe9e-b365-11e7-961e-a94298e5c42f.png)

Followup: The multiples remained even after the update was complete.  Restarting the Pop_Shop app fixed it.
![screenshot from 2017-10-17 18-10-01](https://user-images.githubusercontent.com/1308152/31696508-bb593116-b366-11e7-9cfb-6244dc541943.png)

**Comment by isantop** [comment]
Happened to me too this morning.

**Comment by jackpot51** [comment]
This has been fixed in pop-shop 0.2.6-9
