### ISSUE TITLE
Pop!_Shop should allow search through installed programs

### ISSUE THREAD

**Issue by brs17** [system76/pop-distro#174]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.
```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
Pop!_OS 17.10

**Issue/Bug Description**
User should be able to search through programs already installed on the machine. Currently the search bar is grayed out. 
![screenshot from 2017-10-18 10-59-16](https://user-images.githubusercontent.com/7460774/31732099-82ea1fb4-b3f4-11e7-9d17-9f91de9d2cde.png)

**Comment by WatchMkr** [comment]
You can by searching from Home. Updates doesn't have a search function.

We'll have a separate project for Pop!_Shop improvements which will include reviewing the search functionality overall.
