### ISSUE TITLE
Clarify Readme / Website

### ISSUE THREAD

**Issue by smiller171** [system76/pop-distro#176]
I just heard about this project today (launch day) and the availability of information is really poor. I can't immediately tell if this is a from scratch distro or an Ubuntu spin, or a downstream fork, etc. I don't see an easy way to tell what package management I will find once I install, or any other technical details that would influence my decision to try a new distro or not. I feel like the readme and/or the website really needs a lot more technical information to be useful to people already familiar with Linux.

**Comment by WatchMkr** [comment]
Thanks for your feedback! The Pop tech page has some helpful information and we'll be expanding our documentation over time.

https://system76.com/pop/tech
