### ISSUE TITLE
Unetbootin will not start

### ISSUE THREAD

**Issue by Appalbarry** [system76/pop-distro#177]
barryrueger@pop-os:~$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/system76/pop-distro/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

 * Related Application and/or Package Version - apt policy $PACKAGE NAME
barryrueger@pop-os:~$ apt policy unetbootin
unetbootin:
  Installed: 608-1
  Candidate: 608-1
  Version table:
 *** 608-1 500
        500 http://us.archive.ubuntu.com/ubuntu artful/universe amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description**
Unetbootin will start, but stops before before loading entirely. See image.
![screenshot from 2017-10-19 18-47-04](https://user-images.githubusercontent.com/1308152/31801649-680419d8-b4fe-11e7-9c23-196664a0700d.png)

**Steps to reproduce (if you know)**
1) Install Pop!_OS
2) Open Pop_Shop
3) Find and install Unetbootin
4) Close Pop_Shop and launch Unetbootin
5) Unetbootin starts to open, then stops with a blank pane.

**Expected behaviour**
Unetbootin will launch fully.

**Other Notes**
I actually found this with 17.04 this evening when I went to write the new ISO to a USB stick.
Once I had a fresh install of 17.10 on my machine I tried Unetbootin again with no success.
FWIW, Startup Disk Creator, also installed from Pop_Shop, also seems to not work.
![screenshot from 2017-10-19 18-56-45](https://user-images.githubusercontent.com/1308152/31801815-731c2cc4-b4ff-11e7-9cf4-16fbb52f8346.png)

**Comment by isantop** [comment]
Startup disk creator has been broken for a long time in Ubuntu. As a workaround for now, the Disk Utility has a built-in image writer that works great. You can get to it by opening Disks, clicking on the USB from the list on the left, then clicking on the headerbar menu and choosing "Restore disk image".

**Comment by isantop** [comment]
It looks like the problem unetbootin has is that it still uses gksu, which has long been deprecated. It may not be possible to use it anymore unless the developers update it to use PolicyKit.

**Comment by Appalbarry** [comment]
I'm coming in after years of using Synaptic on Mint, so there maybe some underlying (Gnome?) logic that I don't understand.  I had assumed that the applications available in the Pop_Shop were in some way checked to work with the Pop_OS.  I'm also used to Synaptic identifying missing dependencies and asking I wish to install them.

I'm wondering what benefit Pop_Shop offers that makes it a better choice than Synaptic or other software managers, aside from looking very user friendly.
