### ISSUE TITLE
GNOME Initial Setup

### ISSUE THREAD

**Issue by ahoneybun** [system76/pop-distro#179]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

Walk though the setup and makes account when they exit the setup and logout their login detail do not work.

If they reboot they Initial Setup starts again.

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
**Issue/Bug Description**

GNOME Initial Setup pops up again and again

**Steps to reproduce (if you know)**
Walk though the setup and makes account when they exit the setup and logout their login detail do not work.

If they reboot they Initial Setup starts again.

**Expected behaviour**

Able to log in to their computer

**Other Notes**

Happens every time even if they installed 3 times over and over.

**Comment by jackpot51** [comment]
What username was used?

**Comment by brs17** [comment]
Not enough information to recreate, closing bug.
