### ISSUE TITLE
Make Pop a Truly Free (as in free speech) Distro

### ISSUE THREAD

**Issue by davidpgil** [system76/pop-distro#18]
Will Pop OS be a freedom-respecting OS recommended by the FSF (fsf.org)? Will there be an option to offer freedom-respecting versions of the OS?

I say that there should be a version of the OS that is like Trisquel (trisquel.info). Trisquel is a GNU/Linux distro based off of Ubuntu that removes all non-free drivers and software from it. The FSF endorses it and its a truly freedom respecting platform.

In fact, Trisquel is even on Github. Maybe use it to make Pop: https://github.com/trisquelgnulinux/trisquel-packages

**Comment by WatchMkr** [comment]
I think there are ways to achieve this while also serving our customers that need the best performance from their nVidia GPU - for example. It's unfortunate we have to decide between the two but that's where things are now. It's up for discussion and we'll open to ideas to achieve both.

**Comment by davidpgil** [comment]
Why not have an option?

**Comment by WatchMkr** [comment]
That might be just how it's done. Maybe a checkbox during install or a separate spin.

**Comment by davidpgil** [comment]
[Nouveau: Accelerated Open Source driver for nVidia cards](https://nouveau.freedesktop.org/wiki)

**Comment by djordan2** [comment]
I think a checkbox or separate spin would be good options.  We do actively work with the Nouveau team to improve the install/first-use experience with the latest hardware.  That said, many of our customers do need the binary nvidia drivers.

**Comment by lachlan-00** [comment]
This seems really out of scope for what pop will actually cover as an OEM OS.

The FSF doesn't recommend Debian even though the default install is completely free.

**Comment by nucksmann** [comment]
FSF doesn't endorse anything that recommends non-free firmware, binaries or repositories. Debian does all that, although technically it is free.

**Comment by Parudas** [comment]
An option to provide an installation that only consists out of libre software would be really great.
Might make Pop a distribution for the privacy conscious and for people that enjoy working with and developing libre software.
Trisquel and other libre software distributions often suffer from bad UI, something Pop could tackle.
Of course the regular install should still contain all the neccessary OEM drivers.

**Comment by davidpgil** [comment]
I think a good compromize could be that there be script/wizard that could remove all non-free elements of the install if so desired. Currently, someone wrote a script that will "[Trisiquelize](https://trisquel.info/en/wiki/migrate-ubuntu-trisquel-without-reinstalling)" or "free" and Ubuntu install and turn it into Trisquel.

I think there also may be a fundamental misunderstanding here about what I mean by "free software", please allow [Richard Stallman](https://www.youtube.com/watch?v=ZPPikY3uLIQ) to explain for about 7 minutes.

**Comment by Lesik** [comment]
I would very much like Pop to be a truly freedom-respecting distro, or at least have an easy configuration option for that.

**Comment by Lesik** [comment]
Given that most devices running Pop will be System76 machines, and System76 is also the developer of Pop, this would allow for great integration between the machine and the OS (similar to what OS X is to Macs). For example, the installer could detect what System76 machine the OS is being installed on, and for machines that do not require proprietary firmware to function, for example computers with Intel GPUs like the Galago Pro, it would automatically install a libre Pop.

**Comment by Allanitomwesh** [comment]
Pop OS being FSDG compliant would be great, but you would probably have to have this as a spin. The reason is pretty simple, you cannot recommend a repo with non free software in it. If the proprietary nvidia drivers come with the OS and the ON switch is readily available, i highly doubt FSF will approve. But, if there is a spin, where the non-free repo is manual work, with warnings all the way SUCH THAT THE USER IS CLEARLY AWARE THERE BE DRAGONS AHEAD, then the FSF will likely approve.

**Comment by Allanitomwesh** [comment]
And of corse for the above to work you'd have seperate all proprietary software from the main repo, like how Debian and Fedora do it (No manjaro style pre-installed Steam). You'd just need a spin with a deblobbed kernel (debian main or linux-libre) and a script that warns the user if they attempt to fetch proprietary software (parabola your_freedom package)

**Comment by WatchMkr** [comment]
Thanks for the feedback everyone. We'll keep this in mind as the roadmap develops.
