### ISSUE TITLE
Capslock no longer disabled with Gnome Tweaks

### ISSUE THREAD

**Issue by Appalbarry** [system76/pop-distro#181]
This worked with 17.04, but now doesn't. 
```
barryrueger@pop-os:~$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/system76/pop-distro/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

barryrueger@pop-os:~$ apt policy tweak
tweak:
  Installed: (none)
  Candidate: 3.02-1
  Version table:
     3.02-1 500
        500 http://us.archive.ubuntu.com/ubuntu artful/universe amd64 Packages

```
**Issue/Bug Description**
Previously if CapLock was disabled using the Gnome Tweaks app, it worked.
Since installing 17.10 setting the CapsLock to "Disabled" does nothing.

**Steps to reproduce (if you know)**
a) Install latest version of Pop_OS
b) Install Gnome Tweaks using PopShop
c) Open Gnome Tweaks, navigate to mouse and keyboard settings, and check "Disabled" under CapsLock

![screenshot from 2017-10-21 12-26-26](https://user-images.githubusercontent.com/1308152/31855259-81775100-b65c-11e7-9b71-9f1b325ed429.png)

CapsLock is not disabled.

**Expected behaviour**

CapsLock is disabled.

**Other Notes**

**Comment by brs17** [comment]
@Appalbarry If you want to disable Caps Lock, you need to select the 5th option on that menu, "Caps Lock is disabled". The default "disabled" selection just refers to having any special behaviors disabled for Caps Lock.

**Comment by Appalbarry** [comment]
Bah! My mistake. Though it's arguably confusing.

Barry

On Oct 23, 2017 07:36, "Ben S" <notifications@github.com> wrote:

@Appalbarry <https://github.com/appalbarry> If you want to disable Caps
Lock, you need to select the 5th option on that menu, "Caps Lock is
disabled". The default "disabled" selection just refers to having any
special behaviors disabled for Caps Lock.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/system76/pop-distro/issues/181#issuecomment-338679764>,
or mute the thread

**Comment by brs17** [comment]
I won't disagree with you on that. I'd say that wording is something to discuss with the Gnome-tweak team themselves.
