### ISSUE TITLE
Caption text is the wrong color in the Activities Overview

### ISSUE THREAD

**Issue by James5979** [system76/pop-distro#183]
```

$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/system76/pop-distro/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

$ apt policy pop-gnome-shell-theme
pop-gnome-shell-theme:
  Installed: 2.2.2.1
  Candidate: 2.2.2.1
  Version table:
 *** 2.2.2.1 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu artful/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu artful/main i386 Packages
        100 /var/lib/dpkg/status

```

**Issue/Bug Description**

Bug related to the GNOME Shell pop.css theme. Captions have white text on white backgrounds within the the Activities Overview.

**Steps to reproduce**

Go to the Activities Overview by clicking on the 'Activities' button, and hover the mouse cursor over an open window. You will notice a small caption beneath the window, which will have white text on a white background. You cannot see the text.

**Expected behaviour**

The text should be a dark color on a white background, like the rest of the theme. Then you'll be able to see the text.

**Other Notes**

I managed to fix this on my system by editing a line within the 'pop.css' file:

```

$ sudo vim /usr/share/gnome-shell/theme/pop.css
________                         

[...]                            
/* OVERVIEW */                   
[...]                            
.window-caption {                
  spacing: 25px;                 
  /* color: #FFFFFF; */ /* <--- This line had the incorrect Hex string */                                                              
  color: #574F4A;                
  background-color: #F5F5F5;     
  border-radius: 2px;            
  padding: 4px 8px;              
}                                
[...]                            
________

```

**Comment by brs17** [comment]
@isantop As I understand it, the background text for this window caption needs to be updated. Looks like a pretty quick fix

**Comment by isantop** [comment]
Yep, not sure where that line got changed. It's fixed in git and will be rolling out to Debian in the next round of updates.
