### ISSUE TITLE
Can't remove online accounts from settings

### ISSUE THREAD

**Issue by Filthy-Commie** [system76/pop-distro#184]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/system76/pop-distro/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
```

**Issue/Bug Description**
When I remove my google account from the online accounts panel in system settings, it doesn't actually remove the account, which can be seen when I go to another settings panel, then return to the online accounts panel, where it still shows my account as registered.  It then proceeds to crash after a few seconds.

![2017-10-23 12-20-52](https://user-images.githubusercontent.com/32339182/31903528-fa07649c-b7ed-11e7-9375-2c48f873d67e.gif)
(sorry for the shitty quality gif, had to use some online converter in a pinch.)

**Steps to reproduce (if you know)**
1. Be signed into google account (not sure if same issue with other accounts, haven't tried) from online accounts system settings panel.

2. Remove account by clicking on it, and selecting "Remove Account".

3. Go to other settings panel, then return to Online Accounts.  See the account is still listed, and settings crashes after a few seconds.

**Expected behaviour**
It should actually remove the account.

EDIT: It seems to have fixed itself somehow? I'll leave the issue here because it wasn't acting as it should have for a while.

**Comment by brs17** [comment]
@Filthy-Commie I too can no longer reproduce this bug. In my attempt to recreate however I think I found another bug, where the user should be asked to reenter credentials when reconnecting a media account. Bug: #187
