### ISSUE TITLE
Desktop icon as a first class citizen feature

### ISSUE THREAD

**Issue by diazbastian** [system76/pop-distro#20]
The new GNOME philosophy doesn't contemplate the desktop view (desktop icons) as a desirable feature, presenting a clean desktop by default, however, over time they have neglected this feature that provides by nautilus, creating a separate process for this and not considering new improvements, manifesting their disinterests in gnome bugzilla.

However, for many users desktop view is an important element of their workflow, being a very sought after and maintained feature in operating systems such as macOS, Windows or desktop environments such as KDE, Cinnamon, XFCE, MATE and Unity. At the moment only has been [discussed](https://wiki.gnome.org/Apps/Nautilus/Desktop) separate this feature of Nautilus and to create an [extension](https://gitlab.com/csoriano/org.gnome.csoriano.desktopicons). Considering the previous thing, it would be very good that in the custom desktop of Pop! _OS this feature would be included by default offering functions of a modern OS.

**Comment by jlacroix82** [comment]
I agree with this. Some users will be coming from Unity, and will be wondering why their desktop icons aren't showing up anymore.

**Comment by charlesjt** [comment]
Currently the desktop icons work by activating them from the twek-tool, but it really doesn't work at all well, it's good to know that there is at least one initiative to improve that feature and I also think it should be turned on by default in Pop! _OS.

**Comment by ryanleesipes** [comment]
This is a discussion that we should have on the [subreddit](https://reddit.com/r/pop_os) so that we follow the [contribution guidelines](https://github.com/system76/pop-distro/blob/master/CONTRIBUTING.md) and battle-test the idea.
