### ISSUE TITLE
Feature request: Use Tilix as default terminal

### ISSUE THREAD

**Issue by jlacroix82** [system76/pop-distro#21]
Feature request/recommendation:

If this distribution intends on differentiating itself from Ubuntu GNOME, you may want to consider the Tilix terminal emulator. It has features beyond GNOME terminal, and is a much more modern experience.

https://gnunn1.github.io/tilix-web/

**Comment by ryanleesipes** [comment]
I actually agree with this. I use it as my default and it seems much more "GNOME". If we're creating this for developers, let's give them a better experience.

_Sent from my Samsung SM-G950U using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by schwab** [comment]
Just getting hip to tilix and it's nice. Seems to be favored by many in the design/dev scene. So, I'll plus 1 this.

**Comment by kylerschin** [comment]
Agreed. Out of all my fav terminals, Tilix is the best.

**Comment by WatchMkr** [comment]
Thanks for your suggestion. There's a conversation going regarding Tilix here: https://www.reddit.com/r/pop_os/comments/6n4nk9/what_do_you_think_about_making_tilix_the_default/

We're keeping only bugs and enhancements that are on the road map in the Pop!_OS GitHub issue tracker. Thanks!

**Comment by kylerschin** [comment]
@WatchMkr Lol. I made that reddit post.
