### ISSUE TITLE
Bug: Ubiquity: Time zone/location requested twice

### ISSUE THREAD

**Issue by jlacroix82** [system76/pop-distro#23]
During installation, the installer asks you to select your location for the time zone. This is prompted for again after installation, during the first launch utility that comes up. This seems redundant and I'm assuming this wasn't intended.

**Comment by WatchMkr** [comment]
We've been trimming down Ubiquity to reduce duplication (see https://github.com/system76/pop-distro/issues/11). It's crashing when we remove time zone.

**Comment by WatchMkr** [comment]
I'm going to go ahead and close this as we will be addressing the issue in our OS installation project.
