### ISSUE TITLE
Feature Request: Geany as default text editor

### ISSUE THREAD

**Issue by jlacroix82** [system76/pop-distro#24]
Gedit is nice, but Geany is a great text editor that should be considered as the default. It has a lot of great developer tools (such as running/compling code by simply pressing F5) and the interface can be configured to make it cleaner by default (for example, hiding the status pane on the bottom by default, as well as the side panel if you wish to make it take less screen real estate). I think the added features will benefit developers quite a bit.

**Comment by JosephMcc** [comment]
Is Geany still a gtk2 based application? If it is then it's a poor choice since it won't properly support HiDPI.

**Comment by jlacroix82** [comment]
> Is Geany still a gtk2 based application? If it is then it's a poor choice since it won't properly support HiDPI.
That's a good point. My understanding is that Geany does support GTK3. I am not certain though if the Ubuntu build is built against GTK3. If not, perhaps it could be built against GTK3 and added to the S76 repo.

Regardless, if not Geany, we should consider a different text editor, given the number of developers that will likely be targeted with S76 machines. Gedit is okay, but it doesn't really go the extra mile.

**Comment by ryanleesipes** [comment]
These types of requests should become conversations on our subreddit. We are going to let feature requests go through a baptism by fire over there: https://reddit.com/r/pop_os

You can see the method we are going to use to identify feature requests that we are going to focus on here at S76 HQ here: http://pop.system76.com/docs/pop-os-development-approach/
