### ISSUE TITLE
Possible Bug: /etc/os-release may make configuration tools fail to function properly

### ISSUE THREAD

**Issue by jlacroix82** [system76/pop-distro#25]
The file /etc/os-release has been edited to read "Pop_OS". While I certainly understand why you did this, you should also keep in mind this will most likely break configuration tools such as Ansible/Puppet/Chef, as they are not configured to recognize Pop_OS.

For reference, other spins of Ubuntu (Xubuntu, Ubuntu GNOME, etc) do NOT edit this file. This file should only be edited if you are making your own distribution completely (not using Ubuntu's base, and being completely separate similar to Solus).

It's my strong recommendation to not configure this file, as it will only cause challenges to your developer customers that rely on configuring their machines with DevOps tools.

**Comment by jliles** [comment]
The presence of this file causes the Ubuntu 17.04 postgresql package to fail on installation.

**Comment by jackpot51** [comment]
I will probably leave the Ubuntu defaults, which can be seen here:
```
NAME="Ubuntu"
VERSION="17.04 (Zesty Zapus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.04"
VERSION_ID="17.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=zesty
UBUNTU_CODENAME=zesty
```

**Comment by jackpot51** [comment]
This is fixed in https://github.com/system76/pop-distro/commit/49ea0fe5ae8eec3f78a36e544a85b53a391d42f5
