### ISSUE TITLE
Bug: Installation doesn't ask to set host name

### ISSUE THREAD

**Issue by jlacroix82** [system76/pop-distro#26]
It's important to be able to set a host name for the machine during installation, or at least during the first run wizard that comes up. Unfortunately, this is never prompted for.

**Comment by isantop** [comment]
Definitely agree here. As a temporary workaround, the hostname can be set post-installation by clicking on the name in the `Details` section of the Settings.

**Comment by charlesjt** [comment]
Some installers do this, like Anaconda. Maybe it can be added in gnome-initial-setup, I think EndlessOS does this.

**Comment by WatchMkr** [comment]
I don't think host name belongs in installation. It's unnecessary and can be set by the user afterward. Corporate deployments use either tooling to install the OS, or in the case of Pop!, its installer will generate a unique host name (likely the product name and a 4 character unique identifier derived from the MAC address).

I'm going to remove for now. If you'd like to discuss in detail, let's talk via our subreddit.

https://www.reddit.com/r/pop_os/
