### ISSUE TITLE
Feature Request: Provide dash to dock extension

### ISSUE THREAD

**Issue by Parudas** [system76/pop-distro#27]
Many users expect a computer to work with the ever same principle, with an application menu and a taskbar or some kind of dock.
This is why I think it's important to include the Dash to Dock extension, which can then be enabled through the GNOME Tweaks tool.
It basically allows one to let the sidebar in the activities menu behave like a dock.

Side note:
For easy installation of shell addons from https://extensions.gnome.org/, it's also important to provide the GNOME Shell integration browser extension in firefox.

**Comment by charlesjt** [comment]
It would be better for System76 to conduct a general survey based on the needs of its customers to determine a set of useful and well-maintained extensions that enrich the user experience in Pop! _OS.

**Comment by isantop** [comment]
Surveys don't take the place of actual design and user testing. Design-by-survey is just a thinly veiled form of design by committee, which almost always results in a sub-par product. That said, we definitely appreciate the feedback, and we'll be looking at all feature requests with a scientific eye starting next week when our user-testing period commences.

**Comment by charlesjt** [comment]
@isantop Of course, but don't underestimate a survey or think that it can't be a scientific tool to obtain information. The idea is to have more reliable information about the needs of System76 customers and how they converge with the vision of the System76 engineers.

Otherwise it will open 1 ticket for each extension that a user thinks should go by default because it improves their workflow, considering that the extensions platform is part of GNOME and that anyone can install them at any time.

**Comment by jlacroix82** [comment]
I agree with @isantop in regards to the survey. That's not really a valid way of getting user feedback. A survey should only be used to partially gauge interest, but only user testing can really determine the usefulness. Survey's are biased by default.

Worst case scenario, dash-to-dock can easily be disabled, and if anyone hates it, it will take them less than 10 seconds to turn it off.

**Comment by charlesjt** [comment]
@jlacroix82 It is quite noticeable that you have not done any qualitative study. I don't only speak of users but of "customers". The goal would not be focused on usability but in the first instance to determine whether or not customers use the extensions platform and if so, which extensions they use and why they use it. This would help determine a frame of reference with which to work and determine whether upstream changes will be made to improve the user experience or add an extension, etc.

A bad example of a survey is the one that OMG! Ubunu did, opening it to all public (specialized public that follows their web) with an account and predefining the variables to measure the usability of these.

**Comment by JosephMcc** [comment]
Curious about the user testing. I have an oryx pro I'd gladly install and run this on for awhile :)

**Comment by ryanleesipes** [comment]
We can talk the pros and cons of these extensions over at the subreddit: https://reddit.com/r/pop_os - but we also need to discuss how to best validate which default extensions would improve the experience, you can learn about how we will approach this as a project in the Development Approach doc: http://pop.system76.com/docs/pop-os-development-approach/
