### ISSUE TITLE
Feature request: Software Boutique

### ISSUE THREAD

**Issue by jlacroix82** [system76/pop-distro#28]
I think that the Software Boutique would be a wonderful addition to this distribution. Although Software Boutique is currently specific to Ubuntu MATE, it's being redesigned to not have any requirements on Ubuntu MATE and to instead be completely independent. It's also going to be given features to install any Debian package normally in the repositories, even if it's not featured in the Software Boutique. Once this conversion is finished, you should only need to install the Software Boutique.

This new version of Software Boutique is targeting 17.10, which is also what Pop is targeting. I think this should come up by default during the first run wizard. A welcome screen would be a great asset.

**Comment by WatchMkr** [comment]
Thanks for your suggestion. We'll certainly look at software installation in our user testing and review all the options if testing reveals deficiencies.

We're keeping only bugs and enhancements that are on the road map in the Pop!_OS GitHub issue tracker.

For feature request and brainstorming please join us in our subreddit forum. Thanks!

https://www.reddit.com/r/pop_os/
