### ISSUE TITLE
Makefile 57 error

### ISSUE THREAD

**Issue by e2dubba** [system76/pop-distro#3]
I have tried to build this in a Digital Ocean Droplet, and on a vm, but I get the same error in both:
`Makefile:57: recipe for target 'build/iso_extract.tag' failed`. 
(running ubuntu 16.04 and 17.04 respectively). Am I missing a library?

**Comment by isantop** [comment]
It looks like you might be mission one of the dependencies. Did you run the `deps.sh` script before running the makefile?

**Comment by e2dubba** [comment]
I didn't. And thank you! That helped, but It still hangs up at Makefile line 67. The error message says:
```
cp: cannot stat 'data/default-settings/usr/share/grub/themes': No such file or directory
Makefile:67: recipe for target 'build/iso_modify.tag' failed
```

**Comment by isantop** [comment]
Try a `make clean` and clearing out the contents of your `build/` directory, then running it again. Also, make sure you aren't already providing an ubuntu.iso in that directory.

**Comment by e2dubba** [comment]
I did try the `make clean` and then `make` again. I also removed the ubuntu.iso and ran it again with a fresh image. I still get the second error.

**Comment by jackpot51** [comment]
You need to `git submodule update --init`
