### ISSUE TITLE
Include nvidia driver in the iso

### ISSUE THREAD

**Issue by ejaszewski** [system76/pop-distro#31]
I downloaded the Pop iso from the System76 website and installed it on an 8GB USB 2.0 drive. I then attempted to boot to it from my UEFI on my non-System76 desktop. Everything worked fine until I got to the try or install screen.

After I pressed enter, the screen went black for a couple of seconds, and instead of loading, I got the following error:
```
nouveau 0000:03:00.0: bus: MMIO write of 800000e6 FAULT at 10eb14 [ IBUS ]
nouveau 0000:03:00.0: priv: GPC0: 419df4 00000000 (184082e)
nouveau 0000:03:00.0: priv: GPC1: 419df4 00000000 (184082e)
nouveau 0000:03:00.0: priv: GPC2: 419df4 00000000 (184082e)
nouveau 0000:03:00.0: priv: GPC3: 419df4 00000000 (184082e)
nouveau 0000:03:00.0: fifo: read fault at 00ff880000 engine 1f [] client 12 [PMU] reason 0d [REGION_VIOLATION] on channel -1 [0000000000 unknown]
nouveau 0000:03:00.0: gr: init failed, -110
nouveau 0000:03:00.0: fifo: write fault at 000030b000 engine 05 [BAR2] client 08 [HOST_CPU_NB] reason 0d [REGION_VIOLATION] on channel -1 [00ffbf3000 unknown]
```
The next time I booted, I added the option `modprobe.blacklist=nouveau` to exclude the nouveau driver, and the boot worked fine.

On a probably separate note, I then installed on a 500GB HDD (freshly formatted) and when I try to boot to the 500GB drive, I only get a black screen with a blinking cursor (doesn't even load GRUB).

System Information:
Intel Core i7 4820K @ 3.7 GHz
nVidia GTX 970 (EVGA SC)
16 GB DDR3 memory
500GB Western Digital Blue

**Edit:** I was able to boot to a Linux Mint 18 livecd on the same flash drive. Install also worked, but nouveau was disabled on both the livecd and the installation (defaulted to software rendering). Proprietary driver works fine.

**Comment by WatchMkr** [comment]
As an OEM we experience the iso install problem with nvidia hardware regularly. We will be adding the proprietary nvidia driver to the iso so that installations work without kernel parameters. That will fix the first bug.

I believe the second issue is a bug in Plymouth. We're familiar with it and it may be solved with recent updates. Please run upgrades and if the problem persist, add a separate bug report for nVidia + Plymouth won't boot.

Thanks!

**Comment by ejaszewski** [comment]
Just tested again with the latest version. I was able to boot into the installer and see the "Try or Install Screen", but was unable to progress to the actual OS. I may try again later this week if I have time. I assume that it is related to the Nvidia driver.

**Comment by isantop** [comment]
This topic came up briefly during the Installer Sprint this morning. We're planning on offering both an Nvidia ISO and a Non-Nvidia ISO. Having the Nvidia driver present without Nvidia hardware can cause issues there, so there will need to be two separate ISOs.

**Comment by ejaszewski** [comment]
Makes sense. I'll probably wait until the driver lands before I try again so it doesn't hide any other issues I might have.

**Comment by RicardoEPRodrigues** [comment]
@ejaszewski have you tried booting with `nvidia.modeset=0` or `nouveau.modeset=0` as a parameter in boot options?

It usually fixes it.

**Comment by ejaszewski** [comment]
@RicardoEPRodrigues I tried that the first time. With the ISO I built from master, there were significant graphical glitches with the installer and I abandoned it before I got that far.

**Comment by sarahpandabeara** [comment]
@jackpot51 is this meant for WIP or WIP Beta?

**Comment by jackpot51** [comment]
Probably beta @sarahpandabeara

**Comment by jackpot51** [comment]
We are generating an NVIDIA ISO now.
