### ISSUE TITLE
Feature request: Plotinus

### ISSUE THREAD

**Issue by p-e-w** [system76/pop-distro#32]
Pop aims to be a developer-focused distro. Developers love doing stuff with their keyboard. [Plotinus](https://github.com/p-e-w/plotinus) is a modern approach to keyboard interaction that brings a searchable command palette to every GTK+ 3 application. It supports all GNOME core apps, as well as many others such as LibreOffice and the upcoming GTK3 builds of Inkscape and GIMP. It does *not* require any modifications to these apps in order to work.

![](https://cloud.githubusercontent.com/assets/2702526/20246717/454a1a9a-a9e3-11e6-8b19-4db092348793.gif)

In my (highly biased) opinion, Plotinus offers a keyboard interface that is in many ways superior to classic keyboard shortcuts. It is unobtrusive and only appears when needed, and it would be a nice differentiation factor for a Linux desktop to have.

I therefore propose to ship and enable Plotinus by default in Pop!_OS. This was actually suggested by @ryanleesipes himself in a [recent interview with LifeOnLinux](https://www.lifeonlinux.com/articles/an-interview-with-ryan-sipes-from-system76-about-ubuntu-and-their-future.2) (thanks Ryan!). Since then, Plotinus has gained per-application configurability and a powerful D-Bus API for integration with other software. I now consider Plotinus to be feature complete and am not aware of any major remaining bugs. In other words, I believe it is quite ready to become a default component of Pop.

**Comment by diazbastian** [comment]
And applications that use QT?

**Comment by WatchMkr** [comment]
Thanks for your suggestion. We're keeping only bugs and enhancements that are on the road map in the Pop!_OS GitHub issue tracker.

For feature request and brainstorming please join us in our subreddit forum. Thanks!

https://www.reddit.com/r/pop_os/
