### ISSUE TITLE
Feature Request: Pop! Desktop

### ISSUE THREAD

**Issue by guymanforget** [system76/pop-distro#34]
Currently this uses gnome, but it is ubuntu based and most people wont want an ubuntu based distro with gnome. Luckily, this can be fixed with a custom desktop. It is not too hard, you just need a shell script at the minimum. I recomend a computer specific desktop personally, but anything should work.

**Comment by guymanforget** [comment]
seriously, who like gnome on ubuntu? gnome is good, but people dont want gnome on ubuntu

**Comment by jackpot51** [comment]
At the moment, we are not interested in developing a custom desktop environment.
