### ISSUE TITLE
Feature Request: Find my 76!(iCloud like Find My Device Feature)

### ISSUE THREAD

**Issue by Drisang** [system76/pop-distro#39]
I was thinking what I have on my MBP that I would be giving up if I got rid of MacOS.  Only thing  that came to mind was Find my iPhone, iPad, Mac.    

I would appreciate if there was feature like this to locate a laptop that was lost or stolen.  Option to remotely erase the data.

**Comment by kylerschin** [comment]
Several reasons against this idea.
- The problem with such programs is the fear of a centralized source controlling and monitoring your activity. 
- If such a service is compromised, it could be bad. VERY BAD. 
- If someone did successfully steal a linux laptop, It is very likely to be re-flashed.
- I really don't want to be watched. (and so do you)
- Pretty hard to do. Things can't really be tracked like that.

**Comment by kylerschin** [comment]
Tie a string around your ring finger. That helps.

**Comment by ryanleesipes** [comment]
At this point, this is beyond the scope of the Pop!_OS project. It might be interesting to see if there is a piece of software available for desktop Linux that already does this. I'm marking this closed, but I think that this conversation could be continued at: https://reddit.com/r/pop_os - that is the place for this kind of ideation.
