### ISSUE TITLE
Menu in Totem, Even Visible in Fullscreen

### ISSUE THREAD

**Issue by ryanleesipes** [system76/pop-distro#4]
See below:

![screenshot from 2017-06-21 09-22-41](https://user-images.githubusercontent.com/2141621/27392290-930276ba-5663-11e7-9c4d-3ab32c458d39.png)

This is Fullscreen:
![screenshot from 2017-06-21 09-22-50](https://user-images.githubusercontent.com/2141621/27392305-9881a688-5663-11e7-8932-48ff2456aec7.png)

Apologies for the lack of content on screen, using Wayland.

**Comment by isantop** [comment]
This looks like a problem with Ubuntu patches.

**Comment by jbicha** [comment]
What version of Totem?
What version of Ubuntu?
What desktop?
Have you tried without GNOME Shell extensions?

I don't experience that bug here.

**Comment by ryanleesipes** [comment]
This is fixed.
