### ISSUE TITLE
Font too large when entering encryption key

### ISSUE THREAD

**Issue by TheMonologueGuy** [system76/pop-distro#40]
**Reporter info**
TheMonologueGuy
```
 * Distribution - Pop OS 17.04
 * Related Application and/or Package Version - LUKS encryption
```

**Actual issue**
The encryption works fine, however the font is a bit too large when entering the key.

**Steps to reproduce (if you knew)**
enable encryption of hard drive during setup.
When the computer boots, you'll be prompted with the key. You'll notice the hidden font is a bit big.

**Comment by kylerschin** [comment]
Agreed. I think I can fix it.
