### ISSUE TITLE
ENHANCEMENT: Gnome Extensions

### ISSUE THREAD

**Issue by TheMonologueGuy** [system76/pop-distro#42]
**Reporter info**
This is to keep track of the extensions that are in use by different users to determine what would be good extensions to include by default.

My extensions:
Better volume indicator
No topleft hot corner (Disable Hot Corners refused to work for me)
random walls
removable drive menu
Show desktop from overview
Suspend button
Topicons Plus
User Themes

**Comment by haevalencia** [comment]
I think some things are very specific and should be kept as extensions, however, I think it is better to propose some changes in the main branch, for example:

- Hotcorner management can be included in gnome-tweak-tool (On/Off, change the hot corner location, etc.)
- Control center supports random wallpaper, however, it would be nice to be able to create customized by the user.
- One method to extract removable disks is being considered in the main branch: [Bug 768067](https://bugzilla.gnome.org/show_bug.cgi?id=768067) or [Bug 747876](https://bugzilla.gnome.org/show_bug.cgi?id=747876)

I think that the extensions platform should be more publicized, for example by adding an additional page in gnome-initial-setup that shows the extensions available in the system (to keep them activated or deactivated at the moment) and a link to the project web.

**Comment by sixpounder** [comment]
Just one thought on this: extensions are "personal", and depends mostly on your personal workflow style.

However, in the spirit of the "stay out of the way" interface of pop, it would be reasonable to include TopIcons by default, since it force an already used part of the screen to render stuff that would otherwise require additional screen space on the bottom.

**Comment by diazbastian** [comment]
@sixpounder I think [TopIcons](https://extensions.gnome.org/extension/495/topicons/) and [TopIcons Plus](https://extensions.gnome.org/extension/1031/topicons/) is overrated. Pop! _OS should take advantage of being based on Ubuntu and its AppIndicator support that can achieve better integration and usability, something that [KStatusNotifierItem](https://extensions.gnome.org/extension/615/appindicator-support/) extension achieves much better.

![dropbox](https://user-images.githubusercontent.com/5126124/27974860-c3a6a918-632d-11e7-8507-d15fe7267998.png)

**Comment by diazbastian** [comment]
It would be good to integrate issue #27 here since the approach is more general.

**Comment by ryanleesipes** [comment]
This should be moved to our Subreddit, which is where we are going to have discussions about this type of thing. We need to find ways to figure out what actually improves the default experience. We can also discuss how to best surface great extensions to the user.

Let's start a thread here on extensions: https://reddit.com/r/pop_os

You can refer to our Development Approach here to understand how we'll decide what extensions (if any) become a core part of the experience: http://pop.system76.com/docs/pop-os-development-approach/
