### ISSUE TITLE
Bug/Feature Request: disk encryption has no UI

### ISSUE THREAD

**Issue by kylerschin** [system76/pop-distro#45]
**Reporter info**

```
 * Ubuntu 17.04 zesty
```

**Actual issue**

Disk encryption has no UI, forcing it into a blank terminal to enter the key, followed by more GRUB and Kernel decryption jabber that beginners may not like. 

**Steps to reproduce (if you knew)**

Enable disk encryption on install.

**Expected behaviour**

NO IDEA.

**Other Note (feature-request, question, etc...)**

Up to you how it is. Just don't make me crazy like the Ubuntu one.

Keep it simple.

**Comment by kylerschin** [comment]
https://youtu.be/jE9AxQd7op0

**Comment by kylerschin** [comment]
https://youtu.be/t-TY24xZgZA

**Comment by ryanleesipes** [comment]
@jackpot51 is this something we can actually address?

**Comment by kylerschin** [comment]
lol

**Comment by kylerschin** [comment]
Closing this issue. Appears to work in today's iso.
