### ISSUE TITLE
Ship GNOME MPV as default Video Player

### ISSUE THREAD

**Issue by ryanleesipes** [system76/pop-distro#5]
I would like to point out that I went ahead and tried MPV 3.24 and we should take it under consideration for shipping by default. It is really great and respects all the GNOME-isms we've grown so fond of. ;)

![screenshot from 2017-06-21 09-36-48](https://user-images.githubusercontent.com/2141621/27392926-2e58bd58-5665-11e7-8dd5-9406747c02d2.png)

Also works with Wayland properly for screenshots ^

**Comment by isantop** [comment]
Looks nice, but I think we'll stick with Totem by default as it doesn't add a phantom menu entry (for the standard MPV frontend) and #4  isn't related to Totem itself but rather Ubuntu's patches.
