### ISSUE TITLE
Docker not yet available for zesty OS

### ISSUE THREAD

**Issue by schwab** [system76/pop-distro#50]
```
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

 * Related Application and/or Package Version - apt policy $PACKAGE NAME
sudo apt install docker  or sudo apt install docker-ce
```

**Issue/Bug Description**
With no official docker release for zesty, POP-OS will require the user perform a manual install of docker from binaries.  
https://askubuntu.com/questions/909691/how-to-install-docker-on-ubuntu-17-04
Docker is essential for developers especially if it's to be installed as the primary OS on a development laptop.

**Steps to reproduce (if you know)**

Attempt to follow the docker-ce instructions here : 
https://docs.docker.com/engine/installation/linux/docker-ce/debian/#install-using-the-repository

The step to update the repository will fail with : 
Err:9 https://download.docker.com/linux/debian zesty Release                   
  404  Not Found

**Expected behaviour**

The latest docker should be install-able through the normal apt get install command.

**Other Notes**

**Comment by jackpot51** [comment]
Docker is not required on Zesty, due to it being the docker build host. Install the toolchain from the cookbook instructions instead: https://github.com/redox-os/cookbook

**Comment by jackpot51** [comment]
There is some discussion about this here: https://askubuntu.com/questions/909691/how-to-install-docker-on-ubuntu-17-04

This seems like an issue you should create for docker, not pop-os

**Comment by jackpot51** [comment]
This may be the right place: https://github.com/docker/docker-ce-packaging

**Comment by schwab** [comment]
As a follow up for anyone finding this thread, docker-ce now has apt install support for Zesty 17.04.  I used their documentation [here ](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/) successfully.
