### ISSUE TITLE
Memory Use is Too High

### ISSUE THREAD

**Issue by WatchMkr** [system76/pop-distro#52]
**Reporter info**

```
 * Distribution - (run ```lsb_release -a```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
Pop!_OS 17.04

**Issue/Bug Description**
Memory usage is high compared to other GNOME based distros. Appears related to theming.

**Steps to reproduce (if you know)**
From internal testing at System76 - Pop!_OS does legitimately use 1.4G where Ubuntu uses 1.0G of memory at idle. Switching back to the Adwaita lowers the memory.

**Expected behaviour**
Use equivalent or lower memory than other GNOME based distributions.

**Comment by kylerschin** [comment]
Agreed.... Spending this memory sending data to the NSA? *cough* *cough* Canocial *cough* *cough* 
maybe it's just firefox.
![image](https://user-images.githubusercontent.com/7539174/28429552-f6775e7e-6d31-11e7-8fe7-a3d9e918cce9.png)
![image](https://user-images.githubusercontent.com/7539174/28429581-09ddb652-6d32-11e7-8038-dacdc79a6cd0.png)

**Comment by WatchMkr** [comment]
Fixed with the Pop!_Theme 2 release. Live disc now at 940MB in line with other GNOME distros. (was 1200MB)
