### ISSUE TITLE
Running source /etc/os-release return an error

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [system76/pop-distro#53]
**Reporter info**

```
 * Distribution - (run ```lsb_release -a```)
    Distributor ID:	Ubuntu
    Description:	Ubuntu 17.04
    Release:	17.04
    Codename:	zesty
```

**Issue/Bug Description**

When installing Unreal Engine, their script runs into a problem when trying to run `source /etc/os-release`, which doesn't happen on Ubuntu 16.10.

The error returned is `ubuntu: command not found`.

**Steps to reproduce (if you know)**

Running the following gives you an error.
```
$ source /etc/os-release
ubuntu: command not found
```

**Expected behaviour**

While in the script the command would populate variables like `ID` and `ID_LIKE` that are needed for Unreal Engine.

**Other Notes**

To download the source and install Unreal Engine visit [website](https://wiki.unrealengine.com/Building_On_Linux).

**Comment by jackpot51** [comment]
What are the contents of your `/etc/os-release` ?

**Comment by RicardoEPRodrigues** [comment]
Here goes:

```
NAME="Pop_OS"
VERSION="17.04 (Zesty Zapus)"
ID=pop-os
ID_LIKE=debian ubuntu
PRETTY_NAME="Pop_OS 17.04"
VERSION_ID="17.04"
HOME_URL="http://www.system76.com"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/system76/distro"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=zesty
UBUNTU_CODENAME=zesty
```

**Comment by jackpot51** [comment]
Replace the contents with this:
```
NAME="Ubuntu"
VERSION="17.04 (Zesty Zapus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.04"
VERSION_ID="17.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=zesty
UBUNTU_CODENAME=zesty
```

We have decided against modifying it from the upstream ubuntu for the time being

**Comment by RicardoEPRodrigues** [comment]
It solved the issue. Thank you.

Too bad it bugs out on this...
