### ISSUE TITLE
UEFI Install fails without network due to missing `grub-efi-amd64-signed`

### ISSUE THREAD

**Issue by jackpot51** [system76/pop-distro#6]
This needs to be installed in the live instance or available in the pool

**Comment by jackpot51** [comment]
Fixed by updating the pool from inside the chroot

**Comment by iErebus** [comment]
Hey dude, I'm having this problem and can't even create a bootable USB due to the errors I'm getting right now sadly, could you help me?

**Comment by jackpot51** [comment]
This is an issue that was occuring after booting from the USB stick. Are you sure your issue is related? You may want to create a new issue with details of the problem you are seeing.
