### ISSUE TITLE
Wallpaper stack

### ISSUE THREAD

**Issue by sarahpandabeara** [system76/pop-distro#65]
Cassidy + Kate

**Comment by sarahpandabeara** [comment]
Determine which images we should have other than our typical illustrations. Something that matches with our theme (per Carl : Space Ships)

**Comment by cassidyjames** [comment]
I think it was actually "space shit" 😛

**Comment by cassidyjames** [comment]
I'm working on [a Google Doc](https://docs.google.com/document/d/1z2UqjmfpWL2t4bnrdBMSgbRmwYGltSX6Qr0gOe52foY/edit?usp=sharing) with some guidelines as we develop them. I've also started [an Unsplash collection](https://unsplash.com/collections/1177864/pop) of wallpapers to take a closer look at; these are in no way final, and many might require editing or just not be good fits. I just wanted a place to compile ideas.

**Comment by cassidyjames** [comment]
Alright, Unsplash collection contents have been added to [Dropbox](https://www.dropbox.com/sh/pifbde6ysb15ez1/AAA_DgnDn-hiwUfqKjsueA8_a?dl=0). There are 61 photos, with lots of duplicate ideas (a bunch of similar mountains, etc.). Let's try and narrow that down to the top 12 or so, then we'll need to resize them to ~4K (several are like 8K) and lightly compress them, then include them in the OS.

**Comment by jackpot51** [comment]
Defaults need to be set, and a release to stable.

**Comment by jackpot51** [comment]
Ok, I believe this is handled now.
