### ISSUE TITLE
Add Eddy app

### ISSUE THREAD

**Issue by sarahpandabeara** [system76/pop-distro#66]

**Comment by jackpot51** [comment]
Eddy is currently in staging. We still need to decide for AppCenter and Eddy how we plan to do maintenance.

**Comment by jackpot51** [comment]
I am forking the github project, so we have a better link to use to check for upstream changes and publish them: https://github.com/system76/eddy

**Comment by jackpot51** [comment]
I am putting this into the main Pop repository

**Comment by jackpot51** [comment]
Once this builds: https://launchpad.net/~system76/+archive/ubuntu/pop/+build/13367443

I will test eddy, add it to https://github.com/system76/pop-desktop, and close this issue.

**Comment by jackpot51** [comment]
Eddy added: https://github.com/system76/pop-desktop/commit/925dfa165bd8392aa77de4af2540f4c360fc4655

Waiting on build: https://code.launchpad.net/~system76/+archive/ubuntu/pop/+build/13371478
