### ISSUE TITLE
Remove "help"

### ISSUE THREAD

**Issue by sarahpandabeara** [system76/pop-distro#67]

**Comment by jackpot51** [comment]
This is looking like an impossibility. Many applications depend on the help application. Here are some that would be removed, if we did not have `yelp` installed

- baobab
- eog
- file-roller
- gedit
- gnome-calculator
- gnome-terminal
- language-selector-gnome

**Comment by WatchMkr** [comment]
@jackpot51 Does it require forking to brand or can it be done through configuration? 

Can we use GNOME's upstream version rather than Ubuntu's? D

**Comment by sarahpandabeara** [comment]
I thought @cassidyjames said that they removed it from elementary. Maybe he remembers what they did?

**Comment by cassidyjames** [comment]
@sarahpandabeara elementary OS doesn't ship most of those apps, so it's not a problem there. For File Roller, I believe elementary carries patches for a couple of things anyway, so they presumably patch the Help integration out.

**Comment by WatchMkr** [comment]
Won't fix for 17.10. We'll consider help solutions for 18.04.
