### ISSUE TITLE
Pop session on Xorg by default. Wayland session also available.

### ISSUE THREAD

**Issue by sarahpandabeara** [system76/pop-distro#69]

**Comment by jackpot51** [comment]
This will require modifying GDM3 or overriding its custom.conf file

**Comment by sarahpandabeara** [comment]
Which is the more difficult method of the two?

**Comment by jackpot51** [comment]
Modifying GDM3

**Comment by sarahpandabeara** [comment]
To confirm, do we package GDM ourselves or just pull from Ubuntu?

**Comment by jackpot51** [comment]
I am going to have a patched version with Wayland disabled for the beta. This will not be on Github, the patch will be in a debian source package for now, due to how minor it is

**Comment by jackpot51** [comment]
https://launchpad.net/~system76/+archive/ubuntu/pop-staging/+build/13389921
