### ISSUE TITLE
Theme GDM

### ISSUE THREAD

**Issue by WatchMkr** [system76/pop-distro#7]
GDM Doesn't currently support loading any GNOME shell extensions, which prevents loading the Pop GNOME Shell theme on the login screen. It should allow for loading User Themes, which will allow the login screen to be themed.

**Comment by JosephMcc** [comment]
I'm wondering a bit about direction here. I see you have a fork of gnome-shell. I assume this is so you can patch things to better fit your own use. Is it outside the scope of what you want to do to simply add support for user themes to shell? I've always found it a bit silly that an extension is required to do something as basic as changing the theme.

**Comment by ryanleesipes** [comment]
Should this be renamed to more broadly "Ability to Theme GDM"?

**Comment by WatchMkr** [comment]
Completed in the 17.10 beta (coming soon).
