### ISSUE TITLE
Show dynamic work spaces all the time

### ISSUE THREAD

**Issue by sarahpandabeara** [system76/pop-distro#70]

**Comment by jackpot51** [comment]
Bug report resulting in this behavior: https://bugzilla.gnome.org/show_bug.cgi?id=783953

**Comment by jackpot51** [comment]
Relevant code: https://github.com/GNOME/gnome-shell/blob/master/js/ui/overviewControls.js#L260

**Comment by sarahpandabeara** [comment]
This is not a requirement for the BETA release. Just as an FYI.

**Comment by jackpot51** [comment]
@sarahpandabeara it is important to do discovery on most of these issues to find out how long they would take to fix, and if they can be fixed in a reasonable way.

**Comment by sarahpandabeara** [comment]
agreed, just wanted to make sure that once we get the scope we don't have to hold up the BETA if this isn't ready.

**Comment by jackpot51** [comment]
Handled by https://github.com/system76/gnome-shell-extension-always-show-workspaces

Building here: https://launchpad.net/~system76/+archive/ubuntu/pop-staging/+build/13376440

**Comment by jackpot51** [comment]
Build finished, it is in staging
