### ISSUE TITLE
Suspend button extension

### ISSUE THREAD

**Issue by sarahpandabeara** [system76/pop-distro#71]

**Comment by sarahpandabeara** [comment]
Per David: "Will need to test it on older gnome versions since I have tried to keep it api compatible with 3.24 and earlier as well as 3.25+"

**Comment by jackpot51** [comment]
We only need to deploy it on artful, and that will only be 3.26±

**Comment by jackpot51** [comment]
I am going to debianize it in pop-staging, if it works in 3.26 it will go into pop

**Comment by jackpot51** [comment]
Here is the code: https://github.com/system76/gnome-shell-extension-suspend-button

**Comment by jackpot51** [comment]
Almost ready, waiting on launchpad: https://launchpad.net/~system76/+archive/ubuntu/pop-staging/+build/13389940
