### ISSUE TITLE
[Installer] Cannot get past the location screen when installing offline

### ISSUE THREAD

**Issue by springbov** [system76/pop-distro#73]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**
Not sure what to put here
```
 * Distribution - (run ```lsb_release -a```)
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
(but am on pop os)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
I'm not sure what the name of it is, but it's the installer.
```

**Issue/Bug Description**
After the installation was complete and I reboot my computer into the os I filled out all the information.
When I got to the location screen I clicked on a place near where I live (like I normally do in other debian based installs). However the next button was greyed out. So i tried typing in a city near where I live. no go. No matter what I tried I couldn't get past the screen and a box was with a magnifying glass was stuck in the middle of the screen saying "search for your location".

I hard powered off the computer, hooked up my phone to tether for internet, made sure tethering was in place before the os fully loaded.
When it got to that screen it auto detected a location (which wasn't correct, probably because of an ip look up of some kind), but the next button was no longer greyed out. I filled out the info as I wanted it and proceeded.

**Steps to reproduce (if you know)**
While offline, install pop os
When you get to the location setup (after reboot) try and do get past that set up screen.

**Expected behaviour**
Able to get past the location screen without being online.

**Other Notes**

**Comment by jackpot51** [comment]
There is a bug in GNOME initial setup where you must type your location in the search box and click on it in the dropdown in order to continue, you cannot click on the map

**Comment by springbov** [comment]
I did both.

**Comment by springbov** [comment]
@jackpot51 you were right. I was mistaken. I thought i had done what you said but apparently i didn't. I reinstalled it just to test this and it is not as i had said it.
