### ISSUE TITLE
File searches failing in shell (no results).

### ISSUE THREAD

**Issue by cassidyjames** [system76/pop-distro#74]
Search works in Nautilus.

**Comment by cassidyjames** [comment]
If we don't have tracker installed, that is probably why :wink:

**Comment by cassidyjames** [comment]
I installed tracker locally and rebooted. This now appears to work.

**Comment by jackpot51** [comment]
Fixed in https://github.com/system76/pop-desktop/commit/324a82865d81154509fec0c9c1f959d49a406095
