### ISSUE TITLE
Not having a tray is painful for Dropbox.

### ISSUE THREAD

**Issue by cassidyjames** [system76/pop-distro#75]
> Discussion: Do we stay with upstream or re-enable the hidden tray?
—@sarahpandabeara

**Comment by cassidyjames** [comment]
I strongly recommend sticking with upstream GNOME on this one, as the "system tray" is an artifact from 15 years ago, and has been deprecated for several years. The only reason apps like Dropbox still use it is because distros have shipped backwards-compatible workarounds for a long-deprecated feature.

Dropbox needs to update to support the much-better cloud providers API in GNOME—and very likely will, either officially or in the form of a community solution. Other apps now have standard APIs for notifications, cloud providers, MPRIS, search providers, .desktop actions, etc. for platform integration. Allan Day, the chief GNOME designer, has [written about their reasoning](https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/) and I agree with it wholeheartedly.

If we do decide to continue shipping legacy tray support, we should at least do what Ubuntu is doing, which is [including an appindicator extension](https://launchpad.net/ubuntu/+source/gnome-shell-extension-appindicator/17.10).

**Comment by WatchMkr** [comment]
Is there an extension to add the bottom left tray functionality? In case customers need the crutch before upstream pushes changes and they prefer that functionality to Topicons.

**Comment by jackpot51** [comment]
Not that I have seen @WatchMkr

**Comment by cassidyjames** [comment]
@WatchMkr Ubuntu is shipping their appindicator extension which would probably be what I'd recommend they install if they want a compatibility layer for now.

**Comment by cassidyjames** [comment]
@WatchMkr what do we want to do here: up-up-stream (GNOME) without a tray, or up-stream (Ubuntu) with their appindicator extension?

**Comment by WatchMkr** [comment]
Up-up-stream GNOME. Write an app indicators doc to point users to.

**Comment by jackpot51** [comment]
So, `gnome-shell-extension-appindicator` works well enough. I have been testing it some. This is what I would recommend users install, with `sudo apt install gnome-shell-extension-appindicator`. They can enable it with https://extensions.gnome.org, `gnome-shell-extension-prefs`, or `gnome-tweak-tool`

**Comment by cassidyjames** [comment]
Done in https://github.com/system76/pop-docs/commit/ee2b293e4be2861952ef957eea979609accbd2a1

Live at http://pop.system76.com/docs/status-icons/

**Comment by BenMorel** [comment]
Link is dead  😕 http://pop.system76.com/docs/status-icons/

**Comment by leviport** [comment]
Looks like some stuff got rearranged since that link was shared. Here's where that article lives now: https://support.system76.com/articles/status-icons/

**Comment by BenMorel** [comment]
Thank you! A `301` redirect would have been nice.
