### ISSUE TITLE
NVIDIA brightness hot keys - 10 series

### ISSUE THREAD

**Issue by sarahpandabeara** [system76/pop-distro#80]
System76 drive remove vendor backlight from grub (non-10 series)

**Comment by sarahpandabeara** [comment]
per previous notes in Zoho: This works if we remove the 'acpi_backlight=vendor' boot parameter. We should change this starting with the 17.10 branch of the system76 driver.

**Comment by jackpot51** [comment]
This is in pre-stable now for 17.10. Reminds me that we need to put Pop 17.10 on the imaging server!
