### ISSUE TITLE
HiDPI scaling currently broken in X:

### ISSUE THREAD

**Issue by sarahpandabeara** [system76/pop-distro#81]
- During installation, shell is not scaled
- GNOME initial setup not scaled
- Shell not scaled on first login
- GDM not scaled
- Settings > displays > scaling doesn't work

**Comment by jackpot51** [comment]
Filed a bug: https://bugzilla.gnome.org/show_bug.cgi?id=788049

**Comment by jackpot51** [comment]
Here is an Ubuntu bug: https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1713323

**Comment by jackpot51** [comment]
I found an issue in clutter. There is a setting that should probably be ignored or deprecated called `unscaled-font-dpi`. By ignoring this setting, HiDPI is functional on X11 again.

**Comment by jackpot51** [comment]
```patch
Index: mutter-3.26.0/clutter/clutter/x11/clutter-settings-x11.h
===================================================================
--- mutter-3.26.0.orig/clutter/clutter/x11/clutter-settings-x11.h
+++ mutter-3.26.0/clutter/clutter/x11/clutter-settings-x11.h
@@ -14,7 +14,6 @@ static const struct {
   { "Xft/HintStyle",           "font-hint-style" },
   { "Xft/RGBA",                "font-subpixel-order" },
   { "Fontconfig/Timestamp",    "fontconfig-timestamp" },
-  { "Gdk/UnscaledDPI",         "unscaled-font-dpi" },
 };
```

**Comment by jackpot51** [comment]
https://git.gnome.org/browse/mutter/commit/?id=ea214fb
