### ISSUE TITLE
Re-order the OEM experience

### ISSUE THREAD

**Issue by sarahpandabeara** [system76/pop-distro#84]

**Comment by sarahpandabeara** [comment]
Current state: 
- Choose language
- Network
- Location
- KB language + layout
- User
[Gnome specific]
- Welcome screen w/ nothing but next button
- Keyboard layout
- Privacy (location services)
- Connect to online accounts (broken)
- You're ready to go / Start using Ubuntu button


Future state:
- Choose language
- Network
- Location + privacy (location services)
- KB Language + layout
- User
- Connect to online accounts

**Comment by WatchMkr** [comment]
This has been completed for the 17.10 release and will be superseded by the new installer for 18.04.
