### ISSUE TITLE
Review: Firefox Ubuntu Extension xul-ext-ubufox

### ISSUE THREAD

**Issue by cassidyjames** [system76/pop-distro#88]
> Can this be removed? What functionality do we loose?
—@WatchMkr

**Comment by cassidyjames** [comment]
One thing that it looks like this provides is the Ubuntu-branded start page that we want to get rid of.

**Comment by jackpot51** [comment]
I will remove it. Any others?

**Comment by jackpot51** [comment]
My rationale is that it introduces Ubuntu branding *and* is completely useless.

**Comment by jackpot51** [comment]
This does introduce a few oddities.

Firefox says "Your Firefox is out-of-date", and directs you to the About Firefox page to check for updates. This does not install updates on Ubuntu.

The first page then directs you to sign in to Firefox Sync. Skipping this step leaves you at the start page, although there was already another start page open - now there are two tabs.

**Comment by jackpot51** [comment]
We reenabled it due to having oddities in firefox without it.

**Comment by WatchMkr** [comment]
@jackpot51 now that we've found this extension isn't creating the Firefox out-of-date page, is it okay to remove?

**Comment by jackpot51** [comment]
Yeah, probably.

**Comment by jackpot51** [comment]
I am removing it from the ISO. It will remain on installed systems, as there is no good way to require removal
