### ISSUE TITLE
Convert Pop!_OS page to https

### ISSUE THREAD

**Issue by sarahpandabeara** [system76/pop-distro#89]
Asking people to download an ISO from an insecure page (even if the download itself is over a secure connection) is going to get less acceptable very quickly as we approach an official release.

S3 bucket is probably easiest, but then we lose GitHub edit magic. Might want to look into webhooks when we have more time as we can then use GitHub edit magic AND have it be a secure site.

**Comment by schwab** [comment]
I don't get this one.  Are you worried someone will monitor your traffic in free text and notice you are downloading pop!os?  Is that illegal in your country?  If you're worried about an injection attack or something, they have the md5 hash on the same page, you can check that before burning (a practice I recommend anyway).  Not sure how setting the site to https helps anything else.

**Comment by schwab** [comment]
BTW, just checked, the download is already encrypted, so you should be OK to grab it from anywhere!
