### ISSUE TITLE
GNOME Settings > Details > About > Distro Logo & Version should use distro settings

### ISSUE THREAD

**Issue by WatchMkr** [system76/pop-distro#93]
Need a patch for upstream that users the distro settings to display logo and version instead of what appears to be hard coded info.

**Comment by cassidyjames** [comment]
This won't actually show Pop!_OS so long as our lsb_release is still set to Ubuntu 17.10. Could be fixed with #94

**Comment by jackpot51** [comment]
Fixed in newest pop-default-settings
