### ISSUE TITLE
lsb_release --upstream flag

### ISSUE THREAD

**Issue by cassidyjames** [system76/pop-distro#94]
elementary OS, JoliOS, and Linux Mint have adopted a `-u` or `--upstream` flag to `lsb_release` to display the upstream Ubuntu version, i.e. for install scripts to be able to work better. For example, [Docker checks this flag](https://get.docker.com/) to see if it's a "forked" version and uses that upstream info in place of the normal `lsb_release` output.

We could do the same for Pop!_OS.

**Comment by cassidyjames** [comment]
Also some more info at https://github.com/fmoliveira/lsb-release-upstream

**Comment by WatchMkr** [comment]
At this time we'll use Ubuntu's `lsb_release` data and include Pop information in /etc/os-release
