### ISSUE TITLE
gnome-tweak-tool is missing from the Pop Shop : intentional ?

### ISSUE THREAD

**Issue by 1Claude** [system76/pop-distro#99]
Searching for Tweak in Pop Shop does not reveal Gnome Tweaks. You can see : MATE Tweak, Unity Tweak, but not the one for Gnome.

Is this intentional ?

I was able to install it from the Terminal : sudo apt gnome-tweak-tool And it worked fine.

**Comment by jackpot51** [comment]
It should be called "GNOME Tweaks"

**Comment by 1Claude** [comment]
Ok, you have to be very precised in the search bar, by adding the " - " after gnome. If not, no correct result.

If you only type "gnome tweak", it won't show. Nor if you only type "tweak

**Comment by jackpot51** [comment]
Both "gnome tweak" and "tweak" give me "GNOME Tweaks" as a result. Can I see a screenshot?

**Comment by 1Claude** [comment]
Here you go. :-) 

![tweak](https://user-images.githubusercontent.com/19640810/30992676-10b3fb5c-a479-11e7-93b3-a82346f0185d.png)

![tweak 2](https://user-images.githubusercontent.com/19640810/30992680-172125c8-a479-11e7-9539-59963671a214.png)

![tweak 3](https://user-images.githubusercontent.com/19640810/30992684-1d3c4014-a479-11e7-855c-32f610396c3d.png)

**Comment by jackpot51** [comment]
I wonder if it is being translated, and is searching the translations.

**Comment by 1Claude** [comment]
Hmm...

Might be a clue. But I really don't know. Just your regular user willing to help find bugs.

**Comment by Appalbarry** [comment]
I too wound up installing fgnome tweak from the command line.  The first thing I do with any new install is disable CapsLock, and as far as I can tell this is the only (simple) way to do that.

**Comment by cassidyjames** [comment]
Since this appears to be a bug with Pop!_Shop, I've filed it at https://github.com/system76/pop-distro/issues/99
